(use-modules (ice-9 eval-string))
(use-modules (ice-9 format))

(define (onMouse button action mods) (display ""))
(define (onObjSelected selectedIndex) (display ""))

(define activeLineIndex 0)
(define lineHistory #())
(define cursorFromEnd 0)
(define (appendHistory lineText)
  (set! lineHistory (list->vector (reverse (cons lineText (reverse (vector->list lineHistory))))))
)

(define (executeCommand lineText)
  (cond 
    ((equal? lineText ";clear")  (set! lineHistory #()))
    ((equal? lineText ";quit") (exit))
    (#t (begin 
      (appendHistory lineText)
      (let ((result (eval-string lineText)))
        (appendHistory (format #f "; >result: ~y" result))
      )
    ))
  )
)

(define (splitString line cursorFromEnd)
  (list 
    (substring line 0 (- (string-length line) cursorFromEnd))  
    (substring line (- (string-length line) cursorFromEnd) (string-length line))
  ) 
)

(define currentLineBuffer "")
(define (appendToBuffer value)
  (set! currentLineBuffer (string-append currentLineBuffer value))
)
(define (submitBuffer)
  (executeCommand currentLineBuffer)
  (set! currentLineBuffer "")
  (set! activeLineIndex (vector-length lineHistory))
)
(define (backspaceBuffer)
  (set! currentLineBuffer (substring currentLineBuffer 0 (max 0 (- (string-length currentLineBuffer) 1))))
)
(define (upArrow)
  (if (not (= activeLineIndex 0))
    (begin
      (set! activeLineIndex (- activeLineIndex 1))
      (set! currentLineBuffer (vector-ref lineHistory activeLineIndex))
    )
  )
)
(define (downArrow)
  (if (< activeLineIndex (- (vector-length lineHistory) 1))
    (begin
      (set! activeLineIndex (+ activeLineIndex 1))
      (set! currentLineBuffer (vector-ref lineHistory activeLineIndex))
    )
  )
)
(define (leftArrow)  (set! cursorFromEnd (+ cursorFromEnd 1)))
(define (rightArrow) (set! cursorFromEnd (- cursorFromEnd 1)))


(define (currentLineWithCursor line cursorPos)
  (let ((newString (splitString line cursorPos)))
    (string-append (car newString) "|" (cadr newString))
  )
)
(define (drawFrame numLines fontSize offsetY)
  (define currentHeight 0)
  (draw-text "ModTerminal" 10 (+ offsetY currentHeight) fontSize)
  (set! currentHeight (+ currentHeight 10))
  (draw-text "--------------------------------------" 10 (+ offsetY currentHeight) 1)
  (do ((row (- numLines 1) (- row 1))) ((< row 0))
    (let* ((historyLength (vector-length lineHistory)) (lineIndex (- historyLength row)))
      (if (and (< lineIndex historyLength) (>= lineIndex 0))
        (begin 
          (set! currentHeight (+ currentHeight 10))
          (draw-text (vector-ref lineHistory lineIndex) 10 (+ offsetY currentHeight) fontSize)
        )
      )
    )
  )
  (set! currentHeight (+ currentHeight 10))
  (draw-text "//////////////////////////////" 10 (+ offsetY currentHeight) 2)
  (set! currentHeight (+ currentHeight 10))
  (draw-text (currentLineWithCursor currentLineBuffer cursorFromEnd) 10 (+ offsetY currentHeight) fontSize)
  (set! currentHeight (+ currentHeight 10))
  (draw-text "//////////////////////////////" 10 (+ offsetY currentHeight) 2)
)


(define (onFrame)
  (if showConsole
    (drawFrame 10 4 100)
  )
)

(define showConsole #f)
(define (onKey key scancode action mods)
  (if (and (= key 96) (= action 1))
    (set! showConsole (not showConsole))
  )
  (if showConsole
    (if (and (= action 1) (not (= key 96)))
      (cond
        ((= key 257) (submitBuffer)) 
        ((= key 259) (backspaceBuffer))
        ((= key 265) (upArrow))    
        ((= key 264) (downArrow))   
        ((= key 263) (leftArrow))    
        ((= key 262) (rightArrow))  
        (#t (+ 0 0))
      )
    )
  )
)

(define (onKeyChar key)
  (if (and showConsole (not (= key 96)))
    (appendToBuffer (string (integer->char key)))
  )
)

