
(display "nav scm loaded\n")

(define (onMouse button action mods)
  (define frompos (gameobj-pos mainobj))
  (define nextpos (navpos (gameobj-id mainobj) frompos))
  (define orientation (orientation-from-pos frompos nextpos))

  (display "on mouse called: ")
  (display button)
  (display " ")
  (display action)
  (display " ")
  (display mods)
  (display "\n")
  (display "next pos: ")
  (display nextpos)
  (display "\n")
  ;(gameobj-setpos! mainobj nextpos)
  (display "orientation: ")
  (display orientation)
  (display "\n")
  (gameobj-setpos! mainobj (move-relative frompos orientation 3))
)