(define objSelected #f)
(define hoveringObj #f)

(define currNdi #f)
(define ndiMouseDown #f)
(define objposMouseDown #f)
(define restrictAttrName "dialogmove-restrictx")
(define dialogAttr (assoc restrictAttrName (gameobj-attr mainobj)))
(define restrictXAxis (if dialogAttr (equal? "true" (cadr dialogAttr)) #f))

; should calculate ndi when mouse down, and then on mouse move, this is delta 
; then add delta to gameobj-pos when the pos was down

(define (onDraggableStart)
  (format #t "draggable start dialog move ~a\n" mainobj)
  (sendnotify "dialogmove-drag-start" (number->string (gameobj-id mainobj)))
)
(define (onDraggableRelease)
  (format #t "draggable release dialog move ~a\n" mainobj)
  (sendnotify "dialogmove-drag-stop" (number->string (gameobj-id mainobj)))
)

(define (onMouse button action mods)
  (if (and (equal? button 0) (equal? action 0))
    (begin
      (if objSelected (onDraggableRelease))
      (set! objSelected #f)
      (set! ndiMouseDown #f)
      (set! objposMouseDown #f)
    )
  )
  (if (and (equal? button 0) (equal? action 1) hoveringObj)
    (begin
      (onDraggableStart)
      (set! objSelected #t)
      (set! ndiMouseDown currNdi)
      (set! objposMouseDown (gameobj-pos mainobj))
    )
  )
)

(define (calcNdiOffset)
  (define diffX (- (car currNdi) (car ndiMouseDown)))
  (define diffY (- (cadr currNdi) (cadr ndiMouseDown)))
  (define newx (+ diffX (car objposMouseDown)))
  (define newy (+ diffY (cadr objposMouseDown)))
  (define oldz (caddr objposMouseDown))
  (if restrictXAxis
    (list newx (cadr objposMouseDown) oldz)
    (list newx newy oldz)
  )
)

(define (calculateSnapToGrid ndiOffset cellWidth gridOffset)
  (define xCell (round (/ (car ndiOffset) cellWidth)))
  (define yCell (round (/ (+ (cadr ndiOffset) gridOffset) cellWidth)))
  (define xPos (* cellWidth xCell))
  (define yPos (* cellWidth yCell))
  (format #t "ndi offset: ~a\n" ndiOffset)
  (format #t "cell (x = ~a, y = ~a)\n" xCell yCell )
  (format #t "fcell (x = ~a, y = ~a)\n" xPos yPos )
  (list xPos (- yPos gridOffset) (caddr ndiOffset))
)

(define gridSize (if (args "gridsize") (string->number (args "gridsize")) #f))
(define gridOffset (if (args "gridoffset") (string->number (args "gridoffset")) 0))
(define (onMouseMove xpos ypos ndcx ndcy)
  (set! currNdi (list ndcx ndcy))
  ;(format #t "ndcx: ~a, ndcy: ~a\n" ndcx ndcy)
  (if objSelected 
    (begin
      (gameobj-setpos! mainobj (if gridSize (calculateSnapToGrid (calcNdiOffset) gridSize gridOffset) (calcNdiOffset)))
      (enforce-layout (gameobj-id mainobj))
    )
  )
)

(define (onObjHover obj)
  (define id (gameobj-id obj))
  (if (equal? id (gameobj-id mainobj))
    (set! hoveringObj #t)
  )
)

(define (onObjUnhover obj)
  (define id (gameobj-id obj))
  (if (equal? id (gameobj-id mainobj))
    (set! hoveringObj #f)
  )
)

(enforce-layout (gameobj-id mainobj))