
all:
	@php ./editor.rawscene.php > ./editor.rawscene
	@php ./dock/testpanel.php > ./dock/testpanel.rawscene
	@php ./dock/details.php object_details > ./dock/object_details.rawscene
	@php ./dock/details.php world_state > ./dock/world_state.rawscene
	@php ./dock/details.php object_tools > ./dock/object_tools.rawscene
	@php ./dock/details.php scenegraph > ./dock/scenegraph.rawscene
	@php ./dock/details.php performance > ./dock/performance.rawscene
	@php ./dock/details.php cameras > ./dock/cameras.rawscene
	@php ./dock/details.php lights > ./dock/lights.rawscene
	@php ./dock/details.php sound > ./dock/sound.rawscene
	@php ./dock/details.php not_implemented > ./dock/not_implemented.rawscene

clean:
	@rm ./editor.rawscene
	@rm ./dock/testpanel.rawscene
	@rm ./dock/object_details.rawscene
	@rm ./dock/world_state.rawscene
	@rm ./dock/object_tools.rawscene 
	@rm ./dock/scenegraph.rawscene
	@rm ./dock/performance.rawscene
	@rm ./dock/cameras.rawscene
	@rm ./dock/lights.rawscene
	@rm ./dock/sound.rawscene
	@rm ./dock/not_implemented.rawscene