
all:
	@php ./editor.rawscene.php > ./editor.rawscene
	@php ./dock/testpanel.php > ./dock/editor_testpanel.rawscene
	@php ./dock/details.php object_details > ./dock/editor_object_details.rawscene
	@php ./dock/details.php scene_info > ./dock/editor_scene_info.rawscene
	@php ./dock/details.php object_tools > ./dock/editor_object_tools.rawscene
	@php ./dock/details.php transform > ./dock/editor_transform.rawscene
	@php ./dock/details.php scenegraph > ./dock/editor_scenegraph.rawscene
	@php ./dock/details.php performance > ./dock/editor_performance.rawscene
	@php ./dock/details.php cameras > ./dock/editor_cameras.rawscene
	@php ./dock/details.php lights > ./dock/editor_lights.rawscene
	@php ./dock/details.php sound > ./dock/editor_sound.rawscene
	@php ./dock/details.php text > ./dock/editor_text.rawscene
	@php ./dock/details.php world > ./dock/editor_world.rawscene
	@php ./dock/details.php rendering > ./dock/editor_rendering.rawscene
	@php ./dock/details.php models > ./dock/editor_models.rawscene
	@php ./dock/details.php textures > ./dock/editor_textures.rawscene
	@php ./dock/details.php movement > ./dock/editor_movement.rawscene
	@php ./dock/details.php weapons > ./dock/editor_weapons.rawscene
	@php ./dock/details.php not_implemented > ./dock/editor_not_implemented.rawscene

clean:
	@rm ./editor*.rawscene